Fix some issu

diff --git a/build-all b/build-all
--- a/build-all
+++ b/build-all
@@ -1,17 +1,22 @@
-#!/bin/bash
+#!/bin/env bash
 
 if [[ ! -d scripts ]]; then
     echo "Run script from the top of the repo."
     echo "sudo bash build-all"
     exit 1
 fi
-
+#cleanup(){ 
+#rm -fr "${PWD}"/builddir/ && echo -e "\nDirectory cleaned!";
+#}
+#trap cleanup EXIT
 cd scripts
 
-for script in `ls [0-9][0-9][0-9]-*`; do
+#for script in $(ls [0-9][0-9][0-9]-*); do
+for script in [0-9][0-9][0-9]-* ; do
+    [[ -e "${script}" ]] || exit 1
     echo "Launching ${script}..."
-    ./${script} || exit $?
-    echo ""
+    ./"${script}" || exit $?
+    echo 
 done
 
 echo "Completed!"
